"""your message

Revision ID: 97d9a63da367
Revises: 7d815e993c78
Create Date: 2025-01-22 12:53:14.506001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97d9a63da367'
down_revision = '7d815e993c78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
